# Generated by Django 5.2 on 2025-05-19 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_roles_remove_settings_user_users_generatedpasswords_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="generatedpasswords",
            options={
                "verbose_name": "GeneratedPassword",
                "verbose_name_plural": "GeneratedPasswords",
            },
        ),
        migrations.AlterModelOptions(
            name="roles",
            options={"verbose_name": "Role", "verbose_name_plural": "Roles"},
        ),
        migrations.AlterModelOptions(
            name="settings",
            options={"verbose_name": "Settings", "verbose_name_plural": "Settings"},
        ),
        migrations.AlterModelOptions(
            name="users",
            options={"verbose_name": "User", "verbose_name_plural": "Users"},
        ),
        migrations.RemoveField(
            model_name="generatedpasswords",
            name="password",
        ),
    ]
