# Generated by Django 5.2 on 2025-05-19 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_alter_generatedpasswords_options_alter_roles_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="generatedpasswords",
            name="password",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
    ]
