# Generated by Django 5.2 on 2025-05-20 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_generatedpasswords_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="generatedpasswords",
            name="association",
            field=models.CharField(blank=True, default=" ", max_length=255),
        ),
    ]
