# Generated by Django 5.2 on 2025-05-20 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_alter_generatedpasswords_association"),
    ]

    operations = [
        migrations.AlterField(
            model_name="generatedpasswords",
            name="association",
            field=models.CharField(blank=True, default="асоціація", max_length=255),
        ),
    ]
